export interface Country {
  countryCode: string;
  countryName: string;
  dialCode: string;
  flag: string;
  phonePlaceholder: string;
}

export const COUNTRIES: Country[] = [
  {
    countryCode: "FR",
    countryName: "France",
    dialCode: "+33",
    flag: "🇫🇷",
    phonePlaceholder: "06 12 34 56 78",
  },
  {
    countryCode: "BE",
    countryName: "Belgique",
    dialCode: "+32",
    flag: "🇧🇪",
    phonePlaceholder: "470 12 34 56",
  },
  {
    countryCode: "CH",
    countryName: "Suisse",
    dialCode: "+41",
    flag: "🇨🇭",
    phonePlaceholder: "079 123 45 67",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    dialCode: "+1",
    flag: "🇨🇦",
    phonePlaceholder: "514 234 5678",
  },
  {
    countryCode: "US",
    countryName: "États-Unis",
    dialCode: "+1",
    flag: "🇺🇸",
    phonePlaceholder: "201 555 0123",
  },
  {
    countryCode: "ES",
    countryName: "Espagne",
    dialCode: "+34",
    flag: "🇪🇸",
    phonePlaceholder: "612 34 56 78",
  },
  {
    countryCode: "DE",
    countryName: "Allemagne",
    dialCode: "+49",
    flag: "🇩🇪",
    phonePlaceholder: "151 23456789",
  },
  {
    countryCode: "IT",
    countryName: "Italie",
    dialCode: "+39",
    flag: "🇮🇹",
    phonePlaceholder: "312 345 6789",
  },
  {
    countryCode: "MA",
    countryName: "Maroc",
    dialCode: "+212",
    flag: "🇲🇦",
    phonePlaceholder: "650 123456",
  },
  {
    countryCode: "GB",
    countryName: "Royaume-Uni",
    dialCode: "+44",
    flag: "🇬🇧",
    phonePlaceholder: "7400 123456",
  },
  {
    countryCode: "PT",
    countryName: "Portugal",
    dialCode: "+351",
    flag: "🇵🇹",
    phonePlaceholder: "912 345 678",
  },
  {
    countryCode: "NL",
    countryName: "Pays-Bas",
    dialCode: "+31",
    flag: "🇳🇱",
    phonePlaceholder: "06 12345678",
  },
  {
    countryCode: "LU",
    countryName: "Luxembourg",
    dialCode: "+352",
    flag: "🇱🇺",
    phonePlaceholder: "628 123 456",
  },
  {
    countryCode: "AT",
    countryName: "Autriche",
    dialCode: "+43",
    flag: "🇦🇹",
    phonePlaceholder: "0664 123456",
  },
  {
    countryCode: "IE",
    countryName: "Irlande",
    dialCode: "+353",
    flag: "🇮🇪",
    phonePlaceholder: "085 123 4567",
  },
  {
    countryCode: "PL",
    countryName: "Pologne",
    dialCode: "+48",
    flag: "🇵🇱",
    phonePlaceholder: "512 345 678",
  },
  {
    countryCode: "RO",
    countryName: "Roumanie",
    dialCode: "+40",
    flag: "🇷🇴",
    phonePlaceholder: "0712 345 678",
  },
  {
    countryCode: "GR",
    countryName: "Grèce",
    dialCode: "+30",
    flag: "🇬🇷",
    phonePlaceholder: "691 234 5678",
  },
  {
    countryCode: "SE",
    countryName: "Suède",
    dialCode: "+46",
    flag: "🇸🇪",
    phonePlaceholder: "070 123 45 67",
  },
  {
    countryCode: "NO",
    countryName: "Norvège",
    dialCode: "+47",
    flag: "🇳🇴",
    phonePlaceholder: "406 12 345",
  },
  {
    countryCode: "DK",
    countryName: "Danemark",
    dialCode: "+45",
    flag: "🇩🇰",
    phonePlaceholder: "32 12 34 56",
  },
  {
    countryCode: "FI",
    countryName: "Finlande",
    dialCode: "+358",
    flag: "🇫🇮",
    phonePlaceholder: "041 2345678",
  },
  {
    countryCode: "CZ",
    countryName: "République tchèque",
    dialCode: "+420",
    flag: "🇨🇿",
    phonePlaceholder: "601 123 456",
  },
  {
    countryCode: "HU",
    countryName: "Hongrie",
    dialCode: "+36",
    flag: "🇭🇺",
    phonePlaceholder: "06 20 123 4567",
  },
  {
    countryCode: "SK",
    countryName: "Slovaquie",
    dialCode: "+421",
    flag: "🇸🇰",
    phonePlaceholder: "0912 123 456",
  },
  {
    countryCode: "HR",
    countryName: "Croatie",
    dialCode: "+385",
    flag: "🇭🇷",
    phonePlaceholder: "091 234 5678",
  },
  {
    countryCode: "SI",
    countryName: "Slovénie",
    dialCode: "+386",
    flag: "🇸🇮",
    phonePlaceholder: "031 234 567",
  },
  {
    countryCode: "BG",
    countryName: "Bulgarie",
    dialCode: "+359",
    flag: "🇧🇬",
    phonePlaceholder: "087 123 4567",
  },
  {
    countryCode: "LT",
    countryName: "Lituanie",
    dialCode: "+370",
    flag: "🇱🇹",
    phonePlaceholder: "8612 34567",
  },
  {
    countryCode: "LV",
    countryName: "Lettonie",
    dialCode: "+371",
    flag: "🇱🇻",
    phonePlaceholder: "21 234 567",
  },
  {
    countryCode: "EE",
    countryName: "Estonie",
    dialCode: "+372",
    flag: "🇪🇪",
    phonePlaceholder: "5123 4567",
  },
  {
    countryCode: "CY",
    countryName: "Chypre",
    dialCode: "+357",
    flag: "🇨🇾",
    phonePlaceholder: "96 123456",
  },
  {
    countryCode: "MT",
    countryName: "Malte",
    dialCode: "+356",
    flag: "🇲🇹",
    phonePlaceholder: "9696 1234",
  },
  {
    countryCode: "IS",
    countryName: "Islande",
    dialCode: "+354",
    flag: "🇮🇸",
    phonePlaceholder: "611 1234",
  },
  {
    countryCode: "AL",
    countryName: "Albanie",
    dialCode: "+355",
    flag: "🇦🇱",
    phonePlaceholder: "066 123 4567",
  },
  {
    countryCode: "RS",
    countryName: "Serbie",
    dialCode: "+381",
    flag: "🇷🇸",
    phonePlaceholder: "060 1234567",
  },
  {
    countryCode: "ME",
    countryName: "Monténégro",
    dialCode: "+382",
    flag: "🇲🇪",
    phonePlaceholder: "067 123 456",
  },
  {
    countryCode: "MK",
    countryName: "Macédoine du Nord",
    dialCode: "+389",
    flag: "🇲🇰",
    phonePlaceholder: "070 123 456",
  },
  {
    countryCode: "BA",
    countryName: "Bosnie-Herzégovine",
    dialCode: "+387",
    flag: "🇧🇦",
    phonePlaceholder: "061 123 456",
  },
  {
    countryCode: "TR",
    countryName: "Turquie",
    dialCode: "+90",
    flag: "🇹🇷",
    phonePlaceholder: "0532 123 45 67",
  },
  {
    countryCode: "RU",
    countryName: "Russie",
    dialCode: "+7",
    flag: "🇷🇺",
    phonePlaceholder: "8912 345 67 89",
  },
  {
    countryCode: "UA",
    countryName: "Ukraine",
    dialCode: "+380",
    flag: "🇺🇦",
    phonePlaceholder: "050 123 4567",
  },
  {
    countryCode: "BY",
    countryName: "Biélorussie",
    dialCode: "+375",
    flag: "🇧🇾",
    phonePlaceholder: "029 123 45 67",
  },
  {
    countryCode: "MD",
    countryName: "Moldavie",
    dialCode: "+373",
    flag: "🇲🇩",
    phonePlaceholder: "0621 12345",
  },
  {
    countryCode: "AE",
    countryName: "Émirats arabes unis",
    dialCode: "+971",
    flag: "🇦🇪",
    phonePlaceholder: "050 123 4567",
  },
  {
    countryCode: "SA",
    countryName: "Arabie saoudite",
    dialCode: "+966",
    flag: "🇸🇦",
    phonePlaceholder: "050 123 4567",
  },
  {
    countryCode: "QA",
    countryName: "Qatar",
    dialCode: "+974",
    flag: "🇶🇦",
    phonePlaceholder: "3312 3456",
  },
  {
    countryCode: "KW",
    countryName: "Koweït",
    dialCode: "+965",
    flag: "🇰🇼",
    phonePlaceholder: "5012 3456",
  },
  {
    countryCode: "BH",
    countryName: "Bahreïn",
    dialCode: "+973",
    flag: "🇧🇭",
    phonePlaceholder: "3600 1234",
  },
  {
    countryCode: "OM",
    countryName: "Oman",
    dialCode: "+968",
    flag: "🇴🇲",
    phonePlaceholder: "9212 3456",
  },
  {
    countryCode: "JO",
    countryName: "Jordanie",
    dialCode: "+962",
    flag: "🇯🇴",
    phonePlaceholder: "07 9012 3456",
  },
  {
    countryCode: "LB",
    countryName: "Liban",
    dialCode: "+961",
    flag: "🇱🇧",
    phonePlaceholder: "03 123 456",
  },
  {
    countryCode: "IL",
    countryName: "Israël",
    dialCode: "+972",
    flag: "🇮🇱",
    phonePlaceholder: "050 123 4567",
  },
  {
    countryCode: "EG",
    countryName: "Égypte",
    dialCode: "+20",
    flag: "🇪🇬",
    phonePlaceholder: "0100 123 4567",
  },
  {
    countryCode: "TN",
    countryName: "Tunisie",
    dialCode: "+216",
    flag: "🇹🇳",
    phonePlaceholder: "20 123 456",
  },
  {
    countryCode: "DZ",
    countryName: "Algérie",
    dialCode: "+213",
    flag: "🇩🇿",
    phonePlaceholder: "0551 23 45 67",
  },
  {
    countryCode: "SN",
    countryName: "Sénégal",
    dialCode: "+221",
    flag: "🇸🇳",
    phonePlaceholder: "77 123 45 67",
  },
  {
    countryCode: "CI",
    countryName: "Côte d'Ivoire",
    dialCode: "+225",
    flag: "🇨🇮",
    phonePlaceholder: "01 23 45 67 89",
  },
  {
    countryCode: "CM",
    countryName: "Cameroun",
    dialCode: "+237",
    flag: "🇨🇲",
    phonePlaceholder: "6 71 23 45 67",
  },
  {
    countryCode: "GA",
    countryName: "Gabon",
    dialCode: "+241",
    flag: "🇬🇦",
    phonePlaceholder: "06 12 34 56",
  },
  {
    countryCode: "CG",
    countryName: "Congo",
    dialCode: "+242",
    flag: "🇨🇬",
    phonePlaceholder: "06 123 4567",
  },
  {
    countryCode: "CD",
    countryName: "RD Congo",
    dialCode: "+243",
    flag: "🇨🇩",
    phonePlaceholder: "0812 345 678",
  },
  {
    countryCode: "MG",
    countryName: "Madagascar",
    dialCode: "+261",
    flag: "🇲🇬",
    phonePlaceholder: "032 12 345 67",
  },
  {
    countryCode: "MU",
    countryName: "Maurice",
    dialCode: "+230",
    flag: "🇲🇺",
    phonePlaceholder: "5251 2345",
  },
  {
    countryCode: "RE",
    countryName: "La Réunion",
    dialCode: "+262",
    flag: "🇷🇪",
    phonePlaceholder: "0692 12 34 56",
  },
  {
    countryCode: "ZA",
    countryName: "Afrique du Sud",
    dialCode: "+27",
    flag: "🇿🇦",
    phonePlaceholder: "071 123 4567",
  },
  {
    countryCode: "KE",
    countryName: "Kenya",
    dialCode: "+254",
    flag: "🇰🇪",
    phonePlaceholder: "0712 345678",
  },
  {
    countryCode: "NG",
    countryName: "Nigeria",
    dialCode: "+234",
    flag: "🇳🇬",
    phonePlaceholder: "0802 123 4567",
  },
  {
    countryCode: "GH",
    countryName: "Ghana",
    dialCode: "+233",
    flag: "🇬🇭",
    phonePlaceholder: "023 123 4567",
  },
  {
    countryCode: "JP",
    countryName: "Japon",
    dialCode: "+81",
    flag: "🇯🇵",
    phonePlaceholder: "090 1234 5678",
  },
  {
    countryCode: "CN",
    countryName: "Chine",
    dialCode: "+86",
    flag: "🇨🇳",
    phonePlaceholder: "131 2345 6789",
  },
  {
    countryCode: "KR",
    countryName: "Corée du Sud",
    dialCode: "+82",
    flag: "🇰🇷",
    phonePlaceholder: "010 1234 5678",
  },
  {
    countryCode: "IN",
    countryName: "Inde",
    dialCode: "+91",
    flag: "🇮🇳",
    phonePlaceholder: "081234 56789",
  },
  {
    countryCode: "SG",
    countryName: "Singapour",
    dialCode: "+65",
    flag: "🇸🇬",
    phonePlaceholder: "8123 4567",
  },
  {
    countryCode: "HK",
    countryName: "Hong Kong",
    dialCode: "+852",
    flag: "🇭🇰",
    phonePlaceholder: "5123 4567",
  },
  {
    countryCode: "TW",
    countryName: "Taïwan",
    dialCode: "+886",
    flag: "🇹🇼",
    phonePlaceholder: "0912 345 678",
  },
  {
    countryCode: "TH",
    countryName: "Thaïlande",
    dialCode: "+66",
    flag: "🇹🇭",
    phonePlaceholder: "081 234 5678",
  },
  {
    countryCode: "VN",
    countryName: "Viêt Nam",
    dialCode: "+84",
    flag: "🇻🇳",
    phonePlaceholder: "091 234 56 78",
  },
  {
    countryCode: "MY",
    countryName: "Malaisie",
    dialCode: "+60",
    flag: "🇲🇾",
    phonePlaceholder: "012 345 6789",
  },
  {
    countryCode: "ID",
    countryName: "Indonésie",
    dialCode: "+62",
    flag: "🇮🇩",
    phonePlaceholder: "0812 3456 7890",
  },
  {
    countryCode: "PH",
    countryName: "Philippines",
    dialCode: "+63",
    flag: "🇵🇭",
    phonePlaceholder: "0905 123 4567",
  },
  {
    countryCode: "AU",
    countryName: "Australie",
    dialCode: "+61",
    flag: "🇦🇺",
    phonePlaceholder: "0412 345 678",
  },
  {
    countryCode: "NZ",
    countryName: "Nouvelle-Zélande",
    dialCode: "+64",
    flag: "🇳🇿",
    phonePlaceholder: "021 123 4567",
  },
  {
    countryCode: "BR",
    countryName: "Brésil",
    dialCode: "+55",
    flag: "🇧🇷",
    phonePlaceholder: "011 91234 5678",
  },
  {
    countryCode: "MX",
    countryName: "Mexique",
    dialCode: "+52",
    flag: "🇲🇽",
    phonePlaceholder: "1 55 1234 5678",
  },
  {
    countryCode: "AR",
    countryName: "Argentine",
    dialCode: "+54",
    flag: "🇦🇷",
    phonePlaceholder: "011 15 1234 5678",
  },
  {
    countryCode: "CL",
    countryName: "Chili",
    dialCode: "+56",
    flag: "🇨🇱",
    phonePlaceholder: "09 1234 5678",
  },
  {
    countryCode: "CO",
    countryName: "Colombie",
    dialCode: "+57",
    flag: "🇨🇴",
    phonePlaceholder: "321 1234567",
  },
  {
    countryCode: "PE",
    countryName: "Pérou",
    dialCode: "+51",
    flag: "🇵🇪",
    phonePlaceholder: "912 345 678",
  },
  {
    countryCode: "VE",
    countryName: "Venezuela",
    dialCode: "+58",
    flag: "🇻🇪",
    phonePlaceholder: "0412 1234567",
  },
  {
    countryCode: "EC",
    countryName: "Équateur",
    dialCode: "+593",
    flag: "🇪🇨",
    phonePlaceholder: "099 123 4567",
  },
  {
    countryCode: "UY",
    countryName: "Uruguay",
    dialCode: "+598",
    flag: "🇺🇾",
    phonePlaceholder: "094 123 456",
  },
  {
    countryCode: "PY",
    countryName: "Paraguay",
    dialCode: "+595",
    flag: "🇵🇾",
    phonePlaceholder: "0981 123456",
  },
  {
    countryCode: "BO",
    countryName: "Bolivie",
    dialCode: "+591",
    flag: "🇧🇴",
    phonePlaceholder: "71234567",
  },
];
